# Generated by Django 4.1.4 on 2023-01-05 13:35

import catalog.my_vals
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_bookinstance_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='due_back',
            field=models.DateField(blank=True, null=True, validators=[catalog.my_vals.due_back_validator]),
        ),
    ]
